# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zen = {
    pname = "zen";
    version = "1.17.5b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.17.5b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-X5Q1OuEjbUWE8Y8E446SqvqpoExlTRw9R5TM0esRzP8=";
    };
  };
}
