# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zen = {
    pname = "zen";
    version = "1.17.8b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.17.8b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-17Ruxn4A8tZQ20tuMGJDuDA23yO15M7ff0joVoDUbi4=";
    };
  };
}
